// Code generated by ifacemaker; DO NOT EDIT.

package ifmaker

// Creature ...
type Creature interface {
	// get creatures name
	Name() string
	// get creatures age
	Age() uint8
	// get creatures height
	Height() uint8
	// get creatures weight
	Weight() uint8
	// set creatures name
	SetName(name string)
}
