// Code generated by "stringer -type=OS"; DO NOT EDIT.

package stringer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Windows-0]
	_ = x[Darwin-1]
	_ = x[Linux-2]
}

const _OS_name = "WindowsDarwinLinux"

var _OS_index = [...]uint8{0, 7, 13, 18}

func (i OS) String() string {
	if i >= OS(len(_OS_index)-1) {
		return "OS(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OS_name[_OS_index[i]:_OS_index[i+1]]
}
